#!/usr/bin/env sh
# scripts/deploy.sh
#
# Interactive deployment helper for hideas. Asks the operator for SSO and
# binding details, renders a TOML config file and a docker-compose.yml, builds
# the Docker image, and optionally starts the stack with `docker compose up -d`.
#
# Usage (run from the repository root):
#   ./scripts/deploy.sh             # interactive deploy under ./deploy/
#   ./scripts/deploy.sh /opt/hideas # interactive deploy under /opt/hideas
#
# All generated files are placed under the deployment directory:
#   <dir>/config            hideas config consumed by `hideas serve`
#   <dir>/docker-compose.yml
#   <dir>/data/             persistent SQLite database directory
#
# The script is POSIX sh; it relies on docker (with the compose plugin) being
# installed on the host.

set -eu

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
DEPLOY_DIR=${1:-"${REPO_ROOT}/deploy"}
IMAGE_NAME=${HIDEAS_IMAGE:-hideas:latest}

prompt() {
    label=$1
    default=$2
    if [ -n "$default" ]; then
        printf "%s [%s]: " "$label" "$default" > /dev/tty
    else
        printf "%s: " "$label" > /dev/tty
    fi
    IFS= read -r answer < /dev/tty || answer=""
    if [ -z "$answer" ]; then
        answer=$default
    fi
    printf "%s" "$answer"
}

prompt_required() {
    label=$1
    while :; do
        value=$(prompt "$label" "")
        if [ -n "$value" ]; then
            printf "%s" "$value"
            return
        fi
        printf "  (value is required)\n" > /dev/tty
    done
}

prompt_secret() {
    label=$1
    stty -echo < /dev/tty 2>/dev/null || true
    printf "%s: " "$label" > /dev/tty
    IFS= read -r value < /dev/tty || value=""
    stty echo < /dev/tty 2>/dev/null || true
    printf "\n" > /dev/tty
    printf "%s" "$value"
}

prompt_yes_no() {
    label=$1
    default=$2
    while :; do
        answer=$(prompt "$label (y/n)" "$default")
        case "$answer" in
            y|Y|yes|YES) printf "yes"; return ;;
            n|N|no|NO)   printf "no";  return ;;
        esac
    done
}

random_token() {
    # 32-byte base64-url-safe random string; fall back to /dev/urandom hex.
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -base64 32 | tr -d '\n' | tr '+/' '-_' | tr -d '='
    else
        head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
    fi
}

# Strip a trailing slash, if any. POSIX-safe.
trim_trailing_slash() {
    case "$1" in
        */) printf "%s" "${1%/}" ;;
        *)  printf "%s" "$1" ;;
    esac
}

echo
echo "hideas deployment configuration"
echo "==============================="
echo "Deployment directory: ${DEPLOY_DIR}"
echo

PUBLIC_BASE_URL=$(prompt_required "Public base URL the SSO will redirect to (e.g. https://hideas.example.com/hideas/)")
PUBLIC_BASE_URL=$(trim_trailing_slash "$PUBLIC_BASE_URL")
BASE_PATH=$(prompt "HTTP base_path (must match the URL above)" "/")
case "$BASE_PATH" in
    /*) : ;;
    *)  BASE_PATH="/$BASE_PATH" ;;
esac
case "$BASE_PATH" in
    */) : ;;
    *)  BASE_PATH="$BASE_PATH/" ;;
esac

HOST=$(prompt "Container listen host (use 0.0.0.0 inside Docker)" "0.0.0.0")
PORT=$(prompt "Container listen port" "8765")
PUBLISH_PORT=$(prompt "Host port to publish on" "$PORT")

SSO_ISSUER=$(prompt_required "SSO issuer URL (e.g. https://sso.example.com/oauth)")
SSO_ISSUER=$(trim_trailing_slash "$SSO_ISSUER")
SSO_CLIENT_ID=$(prompt_required "SSO client_id")
SSO_CLIENT_SECRET=$(prompt_secret "SSO client_secret")
SSO_SCOPES=$(prompt "SSO scopes" "openid profile email")

WANT_STATIC=$(prompt_yes_no "Generate a static bearer token (for CI / emergency access)?" "n")
if [ "$WANT_STATIC" = "yes" ]; then
    STATIC_TOKEN=$(random_token)
else
    STATIC_TOKEN=""
fi

# Compute the SSO redirect URL from the public base URL plus the API callback
# path. The hideas server validates this on startup.
REDIRECT_URL="${PUBLIC_BASE_URL}${BASE_PATH#/}api/v1/auth/callback"

mkdir -p "$DEPLOY_DIR" "$DEPLOY_DIR/data"

CONFIG_PATH="$DEPLOY_DIR/config"
COMPOSE_PATH="$DEPLOY_DIR/docker-compose.yml"

# Escape backslashes and double quotes for safe TOML emission.
toml_escape() {
    printf "%s" "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

{
    echo "# Generated by scripts/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo "db = \"/data/hideas.sqlite\""
    echo "host = \"$(toml_escape "$HOST")\""
    echo "port = $PORT"
    echo "base_path = \"$(toml_escape "$BASE_PATH")\""
    if [ -n "$STATIC_TOKEN" ]; then
        echo "token = \"$(toml_escape "$STATIC_TOKEN")\""
    fi
    echo
    echo "[sso]"
    echo "issuer = \"$(toml_escape "$SSO_ISSUER")\""
    echo "client_id = \"$(toml_escape "$SSO_CLIENT_ID")\""
    echo "client_secret = \"$(toml_escape "$SSO_CLIENT_SECRET")\""
    echo "redirect_url = \"$(toml_escape "$REDIRECT_URL")\""
    echo "scopes = \"$(toml_escape "$SSO_SCOPES")\""
} > "$CONFIG_PATH"
chmod 600 "$CONFIG_PATH"

{
    echo "services:"
    echo "  hideas:"
    echo "    image: $IMAGE_NAME"
    echo "    container_name: hideas"
    echo "    restart: unless-stopped"
    echo "    ports:"
    echo "      - \"${PUBLISH_PORT}:${PORT}\""
    echo "    volumes:"
    echo "      - ./config:/etc/hideas/config:ro"
    echo "      - ./data:/data"
} > "$COMPOSE_PATH"

echo
echo "Wrote ${CONFIG_PATH}"
echo "Wrote ${COMPOSE_PATH}"
echo "Redirect URL to register with your SSO:"
echo "  ${REDIRECT_URL}"
if [ -n "$STATIC_TOKEN" ]; then
    echo
    echo "Generated static bearer token (store it somewhere safe; it is also"
    echo "written to ${CONFIG_PATH}):"
    echo "  ${STATIC_TOKEN}"
fi

BUILD_NOW=$(prompt_yes_no "Build the Docker image now (${IMAGE_NAME})?" "y")
if [ "$BUILD_NOW" = "yes" ]; then
    HIDEAS_VERSION=$(prompt "Release version to fetch (or 'latest')" "latest")
    HIDEAS_REPO=$(prompt "GitHub repo to fetch the release from" "lhanlhanlhan/hideas")
    docker build \
        --build-arg HIDEAS_VERSION="$HIDEAS_VERSION" \
        --build-arg HIDEAS_REPO="$HIDEAS_REPO" \
        -t "$IMAGE_NAME" \
        "$REPO_ROOT"
fi

START_NOW=$(prompt_yes_no "Start the stack with docker compose now?" "n")
if [ "$START_NOW" = "yes" ]; then
    (cd "$DEPLOY_DIR" && docker compose up -d)
    echo
    echo "Stack started. Useful next commands:"
    echo "  docker compose -f ${COMPOSE_PATH} logs -f"
    echo "  docker compose -f ${COMPOSE_PATH} down"
else
    echo
    echo "To start later:"
    echo "  cd ${DEPLOY_DIR} && docker compose up -d"
fi
